name: deepin-desktop
version: 15.10
summary: Deepin Desktop.
description: Deepin is an elegant, easy to use and reliable domestic desktop operating system.
  
adopt-info:deepin-desktop

grade: stable
confinement: devmode

architectures:
  - build-on: amd64

apps:
  deepin-desktop:
    command: bash
        slots: [mir, upower-observe]
        plugs:
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - network-manager
        - dde-file-manager
        - udisks2
      
slots:
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
   -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 

parts:
  deepin-desktop:
  deepin:
        stage-packages: [deepin-workspace-wayland, deepin-desktop, gdb, strace, vim, kwin-wayland-backend-x11, libxkbcommon-x11-0, libxkbcommon0, libx11-data, xkb-data, ltrace, kwrite, lxqt-workspace, konsole, kwin-wayland-backend-drm, libqt5sql5-sqlite]
        plugin: dump
        source: empty
        organize:
            usr/bin/Xwayland: usr/bin/Xwayland.orig
    patchy:
        after: [deepin]
        plugin: dump
        source: xwayland
    source: https://github.com/linuxdeepin/dde-file-manager.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME| awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
    build-packages:
      - git
      - sed
